### ISSUE TITLE
0:/UPFG_pdi/src/pdi_tgt_select_main.ks missing

### ISSUE THREAD

**Issue by ThePuzzlemaker** [giuliodondi/kOS-UPFG_PDI#2]
As the title says

Wanted to try this out but it was missing :/

Thanks for your amazing work!

**Comment by giuliodondi** [comment]
I literally made it last night, it's still heavily WIP
I'll do more work on it tonight

**Comment by ThePuzzlemaker** [comment]
No rush, haha, I'm probably gonna have to wait for more docs anyway, have been fiddling but haven't gotten desired results from the PDI script yet
